Photo.create(image_url: "https://www.wachaclub.com/images/bottling_tea_ibuki/ibuki_img_ttl.jpg", product_id: 1)
Photo.create(image_url: "https://www.instagram.com/p/BPkciDiBMgt/media/?size=l", product_id: 1)
Photo.create(image_url: "https://www.projectdesign.jp/201311/images/201311img2/124-01.jpg", product_id: 1)
Photo.create(image_url: "", product_id: 2)
Photo.create(image_url: "", product_id: 2)
Photo.create(image_url: "", product_id: 2)