require './db/seeds/category.rb'
require './db/seeds/brand.rb'
require './db/seeds/condition.rb'
require './db/seeds/delivery_area.rb'
require './db/seeds/shipping_charge.rb'
require './db/seeds/shipping_method.rb'
# require './db/seeds/photo.rb'
# require './db/seeds/product.rb'
require './db/seeds/user.rb'